vars:
  version: &kb_version 'ThinkCorney v1-b1'
units:
  # Key Spacing
  # cx and cy are ergogen's choc spacing units.
  kx: cx
  ky: cy
  kxo: 0.5 * cx
  kyo: 0.5 * cy
  px: kx + 2
  py: ky + 2

  # Keycap Size
  # Ergogen's automatically adds 0.5mm to the cx and cy units
  # to add spacing between the keys.
  # The numbers below are the actual keycap sizes that will be displayed
  # in the pcb to check proper alignment and spacing
  keycaps_x: 17.5
  keycaps_y: 16.5
  keycaps_1_5_x: 26.5
  keycaps_1_5_y: 16.5

  # Nice Nano
  # The nice nano footprint's center doesn't account
  # for the 2.54mm "overhang" of the PCB beyond the pins.
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y
  mcu_xo: 0.5 * mcu_x
  mcu_yo: 0.5 * mcu_y + 0.5 * mcu_overhang_y

  # Nice!View display
  disp_x: 14
  disp_y: 36
  disp_xo: 0.5 * disp_x
  disp_yo: 0.5 * disp_y

  # Trackpoint Mount
  tp_x: 7.8
  tp_y: 23.3
  tp_xo: 0.5 * tp_x
  tp_yo: 0.5 * tp_y

points:
  zones:

    # Main Key Matrix
    matrix:

      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]

      key:
        padding: 1ky
        spread: 1kx
        tags: key

      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
        ring:
          key:
            stagger: 4.75
            column_net: C2
        middle:
          key:
            stagger: 2.375
            column_net: C3
        index:
          key:
            stagger: -2.375
            column_net: C4
        inner:
          key:
            stagger: -2.375
            column_net: C5

      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1

      # Change switch footprints for the keys around the trackpoint mount.
      # These keys need to be soldered and can't use hotswap sockets.
      #
      # Flip so that the socket is further away from the trackpoint mounting
      columns.index.rows.home.tags: key_tp_flipped
      # Flip so that the hotswap pad is not cut off by the trackpoint mounting
      # hole
      columns.index.rows.bottom.tags: key_tp_flipped

    # Thumb Cluster
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
        tags: key
      anchor:
        ref: matrix_index_bottom
        shift: [-9.5, -19.625]
      columns:
        outer:
            key:
              column_net: C3
        home:
            key:
              splay: -15
              spread: 1kx+2
              stagger: -2.7
              column_net: C4
        inner:
            key:
              width: 1.5kx
              splay: 75
              spread: 1kx+2.7
              stagger: 2.3
              tags: key_long
              column_net: C5
      rows:
        # Thumbs only have one row.
        cluster:
          row_net: R4

    controller:
      anchor:
        ref: matrix_inner_top
        shift: [kxo + mcu_xo, kyo -2.25 - mcu_yo]
      key:
        name: mcu
        width: mcu_x
        height: mcu_y

    display:
      anchor:
        ref: mcu
        shift: [0, + mcu_yo - disp_yo ]
      key:
        name: disp
        width: disp_x
        height: disp_y

    trackpoint_mount:
      anchor:
        ref.aggregate.parts:
          - matrix_index_home
          - matrix_index_bottom
          - matrix_inner_home
          - matrix_inner_bottom
        shift: [0, 0]
      key:
        name: tp_mount
        width: tp_x
        height: tp_y

    text_version:
      anchor:
        ref: matrix_pinky_bottom
        shift: [+kxo * 2, -kyo + 1.5]

outlines:

  # Pure key outline.
  raw:
    - what: rectangle
      where: true
      size: [px, py]

  # Key outlines with 0.5mm removed to show key overlaps.
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]

  # Actual outline of the board
  board:
    - what: polygon
      operation: stack
      fillet: 1
      points:

        # Top
        # Outer
        - ref: matrix_outer_top
          shift: [-kxo, +kyo]
        - ref: matrix_outer_top
          shift: [+kxo, +kyo]

        # Pinky
        - ref: matrix_pinky_top
          shift: [-kxo, +kyo]
        - ref: matrix_pinky_top
          shift: [+kxo, +kyo]

        # Ring
        - ref: matrix_ring_top
          shift: [-kxo, +kyo]
        - ref: matrix_ring_top
          shift: [+kxo, +kyo]

        # Middle
        - ref: matrix_middle_top
          shift: [-kxo, +kyo]
        - ref: matrix_middle_top
          shift: [+kxo, +kyo]

        # Index
        - ref: matrix_index_top
          shift: [-kxo, +kyo]
        - ref: matrix_index_top
          shift: [+kxo, +kyo]

        # Inner
        - ref: matrix_inner_top
          shift: [-kxo, +kyo]
        - ref: matrix_inner_top
          shift: [+kxo, +kyo]

        # Controller
        - ref: mcu
          shift: [-mcu_xo, +mcu_yo]
        - ref: mcu
          shift: [+mcu_xo, +mcu_yo]

        # Right Side
        # Inner Thumb
        - ref: thumbs_inner_cluster
          shift: [+1.5kxo, -kyo]
        - ref: thumbs_inner_cluster
          shift: [-1.5kxo, -kyo]

        # Bottom
        # Inner thumb
        - ref: thumbs_inner_cluster
          shift: [-1.5kxo, +kyo]

        # Outer Thumb
        - ref: thumbs_outer_cluster
          shift: [-kxo, -kyo]

        # Pinky y and ring x
        - ref: matrix_pinky_bottom
          shift: [kxo + 1kx, -kyo]

        # Outer
        - ref: matrix_outer_bottom
          shift: [-kxo, -kyo]

  # Combination preview showing outline and keys.
  combo:
    - name: board
    - operation: subtract
      name: keys

pcbs:
  think_corney:
    outlines:
      main:
        outline: board
    footprints:

      # Key Area
      # Regular keys with hotswap
      choc_hotswap:
        what: choc
        where: [key]
        params:
          reverse: true
          hotswap: true
          hotswap_tht: true
          keycaps: true
          keycaps_x: keycaps_x
          keycaps_y: keycaps_y
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [0,0]
          rotate: -180

      # 1.5u thumb key
      choc_hotswap_1_5u:
        what: choc
        where: [key_long]
        params:
          reverse: true
          hotswap: true
          hotswap_tht: true
          keycaps: true
          keycaps_x: keycaps_1_5_x
          keycaps_y: keycaps_1_5_y
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [0,0]
          rotate: -180

      diode:
        what: diode
        where: [key, key_long]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
        adjust:
          shift: [0, 3.8]

      # Prevent cut off of pad by trackpoint mounting hole
      choc_tp_flipped:
        what: choc
        where: [key_tp_flipped]
        params:
          reverse: true
          hotswap: true
          hotswap_tht: true
          keycaps: true
          keycaps_x: keycaps_x
          keycaps_y: keycaps_y
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [0,0]
          rotate: 0

      diode_flipped:
        what: diode
        where: [key_tp_flipped]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
        adjust:
          shift: [0, -3.8]


      # Controller Area
      promicro:
        what: nice_nano_pretty
        params:
          show_labels: true
          label_layer: 'SilkS'

          # Pin Assignments (Controller on top facing down)
          # Right Side
          P0: 'TPD'    # Trackpoint Data
          P1: 'TPC'    # Trackpoint Clock
          # GND
          # GND
          P2: 'DPD'   # Display Data
          P3: 'DPC'   # Display Clock
          P4: 'R1'    # Row Top
          P5: 'R2'    # Row Home
          P6: 'R3'    # Row Bottom
          P7: 'R4'    # Row Thumb
          P8: 'F8'    # Free, but could be Num Row
          P9: 'DPE'   # Display CS (nice!view only)

          # Left Side
          # RAW       # Battery Pos
          # GND       # Ground / Battery Neg
          # RST       # Reset pin
          # VCC       # External Power
          P21: 'C0'   # Column Outer
          P20: 'C1'   # Column Pinky
          P19: 'C2'   # Column Ring
          P18: 'C3'   # Column Middle
          P15: 'C4'   # Column Index
          P14: 'C5'   # Column Inner
          P16: 'F16'  # Free, but could be Encoder 1
          P10: 'F10'  # Free, but could be Encoder 2

        where:
          ref: mcu
          shift: [0,0]
          rotate: -90

      trackpoint_mount:
        what: trackpoint_mount
        params:
          reverse: false
          side: F
          show_outline_t430: true
        where:
          ref: tp_mount

      display:
        what: nice_view
        params:
          reverse: true
          MOSI: DPD
          SCK: DPC
          CS: DPE
          show_labels: true
          jumpers_at_bottom: true
        where:
          ref: disp

      conn_battery:
        what: conn_molex_pico_ezmate_1x02
        params:
          reverse: true
          pad_1: BAT_P
          pad_2: GND
        where:
          ref: mcu
          shift: [0, -mcu_yo - 16.35]
          rotate: 180

      pads_bat:
        what: pads
        params:
          reverse: true
          width: 1.25
          height: 2.5
          space: 1.25
          pads: 2
          net_1: BAT_P
          net_2: GND
        where:
          ref: mcu
          shift: [0, -mcu_yo - 12]
          rotate: -180

      icon_bat:
        what: icon_bat
        params:
          reverse: true
          spacing: 1.5
        where:
          ref: mcu
          shift: [0, -mcu_yo - 10]
          rotate: 180

      conn_trackpoint:
        what: conn_molex_pico_ezmate_1x05
        params:
          reverse: true
          side: F
          pad_1: TP_GND
          pad_2: TP_SCL
          pad_3: TP_SDA
          pad_4: TP_RST
          pad_5: TP_VCC
        where:
          ref: mcu
          shift: [-6, -mcu_yo - 15]
          rotate: -90

      pads_trackpoint:
        what: pads
        params:
          reverse: true
          width: 1
          height: 2
          space: 1
          pads: 5
          net_1: TP_GND
          net_2: TP_SCL
          net_3: TP_SDA
          net_4: TP_RST
          net_5: TP_VCC
          label_1: GND
          label_2: SCL
          label_3: SDA
          label_4: RST
          label_5: VCC
          label_at_bottom: true
        where:
          ref: mcu
          shift: [-6, -mcu_yo - 15]
          rotate: -90

      power_switch:
        what: switch_power
        params:
          reverse: true
          from: BAT_P
          to: RAW
        where:
          ref: mcu
          shift: [6.5, -mcu_yo - 15]
          rotate: 0

      reset_switch:
        what: switch_reset
        params:
          reverse: true
          from: GND
          to: RST
        where:
          ref: mcu
          shift: [6.5, -mcu_yo - 7.75]
          rotate: 0

      text_version:
        what: text
        params:
          reverse: true
          text: *kb_version
        where:
          ref: text_version

      text_jlc_order_num:
        what: text
        params:
          reverse: true
          text: "JLCJLCJLCJLC"
        where:
          ref: text_version
          shift: [0, +1.5]
          rotate: 0

      # reset:
      #   what: button
      #   params:
      #     from: GND
      #     to: RST
      #   where:
      #     ref: mcu
      #     shift: [0, -mcu_yo - 8]
      #     rotate: -90
