vars:
  version: &kb_version 'ThinkCorney v1-b1'
units:
  # Key Spacing
  # cx and cy are ergogen's choc spacing units.
  kx: cx
  ky: cx
  kxo: 0.5 * kx
  kyo: 0.5 * ky
  px: kx + 2
  py: ky + 2

  # Keycap Size
  # Ergogen's automatically adds 0.5mm to the cx and cy units
  # to add spacing between the keys.
  # The numbers below are the actual keycap sizes that will be displayed
  # in the pcb to check proper alignment and spacing
  keycaps_x: 17.5
  keycaps_y: 16.5
  keycaps_1_5_x: 26.5
  keycaps_1_5_y: 16.5
  keycaps_1_5_xo: 0.5 * keycaps_1_5_x
  keycaps_1_5_yo: 0.5 * keycaps_1_5_y

  # This allows the layout to adopt based on whether
  # the inner thumb key is a 1u or 1.5u key
  inner_thumb_x: 1.5 * kx
  inner_thumb_y: ky
  inner_thumb_xo: 0.5 * inner_thumb_x
  inner_thumb_yo: 0.5 * inner_thumb_y

  # PCB Edge Padding
  # Top/Bottom Choc: 0.1
  # Top/Bottom MX: -0.35
  pcb_outline_padding_top: 0.1
  pcb_outline_padding_bottom: 0.1
  pcb_outline_padding_left: 0

  # Choc: 0
  # MX: 0.804
  thumb_inner_move_x: 0

  # Choc: 0
  # MX: -0.230
  thumb_inner_move_y: 0

  # Thumb key splay
  splay_thumb_home: -15
  splay_thumb_inner: 90 + -15

  # Thumb key offset
  # Spacing required for outline to get a straight edge for the inner side
  # MX Spaced: -0.1
  # Choc Spaced: 1.35
  thumb_edge_offset: 1.0

  # Thumb Cluster offset from bottom index finger key
  # MX: -9.5
  # Choc: -8.5
  thumb_cluster_offset_x: -8.5
  thumb_cluster_offset_y: -19.625

  # Font units
  font_x: 1
  font_y: 1
  font_xo: 0.5 font_x
  font_yo: 0.5 * font_y

  # Nice Nano
  # The nice nano footprint's center doesn't account
  mcu_spacing_left: 1.25
  mcu_spacing_right: 1.5
  mcu_x: 17.78
  mcu_y: 33.0
  mcu_xo: 0.5 * mcu_x
  mcu_yo: 0.5 * mcu_y

  # Nice!View display
  disp_x: 14
  disp_y: 36
  disp_jumper_y: 2.6
  disp_xo: 0.5 * disp_x
  disp_yo: 0.5 * disp_y

  # Battery Connector
  batc_x: 4.3
  batc_y: 4.6
  batc_xo: 0.5 * batc_x
  batc_yo: 0.5 * batc_y

  # Battery Pads
  batp_x: 3.75
  batp_y: 2.5
  batp_xo: 0.5 * batp_x
  batp_yo: 0.5 * batp_y

  # Power Switch
  sw_power_x: 3.1
  sw_power_y: 8.3
  sw_power_xo: 0.5 * sw_power_x
  sw_power_yo: 0.5 * sw_power_y

  # Reset Switch
  sw_reset_x: 3.4
  sw_reset_y: 5
  sw_reset_xo: 0.5 * sw_reset_x
  sw_reset_yo: 0.5 * sw_reset_y

  # Trackpoint Mount
  tpm_x: 7.8
  tpm_y: 23.3
  tpm_xo: 0.5 * tpm_x
  tpm_yo: 0.5 * tpm_y

  # Trackpoint Connector
  tpc_x: 9
  tpc_y: 4.8
  tpc_xo: 0.5 * tpc_x
  tpc_yo: 0.5 * tpc_y

points:
  zones:

    #
    # Main Key Matrix
    #
    matrix:

      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]

      key:
        padding: 1ky
        spread: 1kx
        tags: key

      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
        ring:
          key:
            stagger: 4.75
            column_net: C2
        middle:
          key:
            stagger: 2.375
            column_net: C3
        index:
          key:
            stagger: -2.375
            column_net: C4
        inner:
          key:
            stagger: -2.375
            column_net: C5

      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1

      # Change switch footprints for the keys around the trackpoint mount.
      # These keys need to be soldered and can't use hotswap sockets.
      #
      # Flip so that the socket is further away from the trackpoint mounting
      columns.index.rows.top.tags: key_tp_flipped
      # Flip so that the hotswap pad is not cut off by the trackpoint mounting
      # hole
      columns.index.rows.home.tags: key_tp_flipped

    #
    # Thumb Cluster
    #
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
        tags: key
      anchor:
        ref: matrix_index_bottom
        shift: [thumb_cluster_offset_x, thumb_cluster_offset_y]
      columns:
        outer:
            key:
              column_net: C3
        home:
            key:
              splay: splay_thumb_home
              spread: 1kx+2
              stagger: -2.7
              column_net: C4
        inner:
            key:
              width: 1.5kx
              splay: splay_thumb_inner
              spread: 1kx + 2.7 + thumb_inner_move_x
              stagger: 2.3 + thumb_inner_move_y
              tags: key_long
              column_net: C5
      rows:
        # Thumbs only have one row.
        cluster:
          row_net: R4

    #
    #  Controller
    #
    controller:
      anchor:
        ref: matrix_inner_top
        shift: [kxo + mcu_xo + mcu_spacing_left, kyo - mcu_yo + pcb_outline_padding_top]
      key:
        name: mcu
        width: mcu_x
        height: mcu_y

    #
    # Helper Points
    #
    edge_thumb_cluster_top:
      anchor:
        ref: thumbs_inner_cluster
        shift: [+inner_thumb_xo, -inner_thumb_yo - thumb_edge_offset]
      key:
        name: edge_thumb_cluster_top
        # thumbs_inner_cluster is splayed. So here we "unsplay" it
        splay: -splay_thumb_home - splay_thumb_inner

    edge_thumb_cluster_bottom:
      anchor:
        ref: thumbs_inner_cluster
        shift: [-inner_thumb_xo, -inner_thumb_yo - thumb_edge_offset]
      key:
        name: edge_thumb_cluster_bottom

    #
    # Part Positioning
    #

    display:
      anchor:
        ref: mcu
        shift: [0, + mcu_yo - disp_yo ]
      key:
        name: disp
        width: disp_x
        height: disp_y

    battery_conn:
      anchor:
        ref: disp
        shift: [+batc_xo, -disp_yo - disp_jumper_y - batc_yo - 3.5 ]
      key:
        name: batc
        width: batc_x
        height: batc_y

    battery_pad:
      anchor:
        ref: batc
        shift: [0, -batc_yo - batp_yo - 3]
      key:
        name: batp
        width: batp_x
        height: batp_y

    power_switch:
      anchor:
        ref: edge_thumb_cluster_top
        shift: [-sw_power_xo - 0.5, +sw_power_yo + 1]
      key:
        name: sw_power
        width: sw_power_x
        height: sw_power_y

    reset_switch:
      anchor:
        ref: sw_power
        shift: [+sw_power_xo - sw_reset_xo - 0.1, +sw_power_yo + 2 + sw_reset_yo]
      key:
        name: sw_reset
        width: sw_reset_x
        height: sw_reset_y

    trackpoint_mount:
      anchor:
        ref.aggregate.parts:
          - matrix_index_top
          - matrix_index_home
          - matrix_inner_top
          - matrix_inner_home
        shift: [0, 0]
      key:
        name: tp_mount
        width: tpm_x
        height: tpm_y

    trackpoint_connector:
      anchor:
        ref: matrix_inner_bottom
        shift: [+kxo + tpc_xo + 0.75, -kyo - tpc_yo + 0.5]
      key:
        name: tp_conn
        width: tpm_x
        height: tpm_y

    text_version:
      anchor:
        ref: matrix_pinky_bottom
        shift: [+kxo * 2, -kyo + 1.5]

pcbs:
  think_corney:
    outlines:
      main:
        outline: board
    footprints:

      # Controller
      promicro:
        what: infused-kim/nice_nano_pretty
        params:
          traces: true
          show_labels: false

          # Pin Assignments (Controller on top facing down)
          # Right Side
          P0: 'TPD'    # Trackpoint Data
          P1: 'TPC'    # Trackpoint Clock
          # GND
          # GND
          P2: 'DPD'   # Display Data
          P3: 'DPC'   # Display Clock
          P4: 'R1'    # Row Top
          P5: 'R2'    # Row Home
          P6: 'R3'    # Row Bottom
          P7: 'R4'    # Row Thumb
          P8: 'F8'    # Free, but could be Num Row
          P9: 'DPE'   # Display CS (nice!view only)

          # Left Side
          # RAW       # Battery Pos
          # GND       # Ground / Battery Neg
          # RST       # Reset pin
          # VCC       # External Power
          P21: 'C0'   # Column Outer
          P20: 'C1'   # Column Pinky
          P19: 'C2'   # Column Ring
          P18: 'C3'   # Column Middle
          P15: 'C4'   # Column Index
          P14: 'C5'   # Column Inner
          P16: 'F16'  # Free, but could be Encoder 1
          P10: 'F10'  # Free, but could be Encoder 2
        where:
          ref: mcu
          shift: [0,0]

      # Key Area
      # Regular keys with hotswap
      choc_hotswap:
        what: infused-kim/choc
        where: [key]
        params:
          reverse: true
          hotswap: true
          hotswap_tht: true
          keycaps: true
          keycaps_x: keycaps_x
          keycaps_y: keycaps_y
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [0,0]
          rotate: -180

      # 1.5u thumb key
      choc_hotswap_1_5u:
        what: infused-kim/choc
        where: [key_long]
        params:
          reverse: true
          hotswap: true
          hotswap_tht: true
          keycaps: true
          keycaps_x: keycaps_1_5_x
          keycaps_y: keycaps_1_5_y
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [0,0]
          rotate: -180

      diode:
        what: infused-kim/diode
        where: [key, key_long]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
        adjust:
          shift: [0, 3.8]

      # Prevent cut off of pad by trackpoint mounting hole
      choc_tp_flipped:
        what: infused-kim/choc
        where: [key_tp_flipped]
        params:
          reverse: true
          hotswap: true
          hotswap_tht: true
          keycaps: true
          keycaps_x: keycaps_x
          keycaps_y: keycaps_y
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          shift: [0,0]
          rotate: 0

      diode_flipped:
        what: infused-kim/diode
        where: [key_tp_flipped]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
        adjust:
          shift: [0, -3.8]


      # Controller Area
      trackpoint_mount:
        what: infused-kim/trackpoint_mount
        params:
          reverse: true
          show_outline_t430: false
          show_outline_x240: true
        where:
          ref: tp_mount

      display:
        what: infused-kim/nice_view
        params:
          reverse: true
          MOSI: DPD
          SCK: DPC
          CS: DPE
          show_labels: true
          jumpers_at_bottom: true
        where:
          ref: disp

      conn_battery:
        what: infused-kim/conn_molex_pico_ezmate_1x02
        params:
          reverse: true
          pad_1: BAT_P
          pad_2: GND
        where:
          ref: batc
          rotate: 180

      conn_battery_icon:
        what: infused-kim/icon_bat
        params:
          reverse: true
          spacing: 1.5
        where:
          ref: batc
          shift: [0, batc_yo + font_yo + 0.5]
          rotate: 180

      pads_bat:
        what: infused-kim/pads
        params:
          reverse: true
          width: 1.25
          height: 2.5
          space: 1.25
          pads: 2
          net_1: BAT_P
          net_2: GND
        where:
          ref: batp
          rotate: -180

      pads_bat_icon:
        what: infused-kim/icon_bat
        params:
          reverse: true
          spacing: 1.5
        where:
          ref: batp
          shift: [0, batp_yo + font_yo + 0.3]
          rotate: 180

      conn_trackpoint:
        what: infused-kim/conn_molex_pico_ezmate_1x05
        params:
          reverse: true
          side: F
          pad_1: VCC
          pad_2: GND
          pad_3: TPC
          pad_4: TPR
          pad_5: TPD
        where:
          ref: tp_conn
          rotate: 180

      pads_trackpoint:
        what: infused-kim/pads
        params:
          reverse: true
          width: 1
          height: 2
          space: 1
          pads: 5

          net_1: VCC
          net_2: GND
          net_3: TPC
          net_4: TPR
          net_5: TPD

          label_1: VCC
          label_2: GND
          label_3: SCL
          label_4: RST
          label_5: SDA
          label_at_bottom: true
        where:
          ref: tp_conn
          shift: [0, 0]
          rotate: 180

      trackpoint_reset_circuit:
        what: infused-kim/smd_0805
        params:
          reverse: true
          space: 1
          mirror: true
          label_at_bottom: true
          swap_pad_direction: true
          components: 4

          # TP clock pull up resistor 4.7k
          net_1_from: TPC
          net_1_to: VCC
          label_1: TCR

          # TP Reset circuit resistor 100k
          net_2_from: TPR
          net_2_to: GND
          label_2: TRR

          # TP Reset circuit capacitor 2.2uF
          net_3_from: TPR
          net_3_to: VCC
          label_3: TRC

          # TP data pull up resistor 4.7k
          net_4_from: TPD
          net_4_to: VCC
          label_4: TDR

        where:
          ref: tp_conn
          shift: [0, 6]
          rotate: 180

      power_switch:
        what: infused-kim/switch_power
        params:
          reverse: true
          from: BAT_P
          to: RAW
        where:
          ref: sw_power
          rotate: 0

      reset_switch:
        what: infused-kim/switch_reset
        params:
          reverse: true
          from: GND
          to: RST
        where:
          ref: sw_reset
          rotate: 0

      text_version:
        what: infused-kim/text
        params:
          reverse: true
          text: *kb_version
        where:
          ref: text_version

      text_jlc_order_num:
        what: infused-kim/text
        params:
          reverse: true
          text: "JLCJLCJLCJLC"
        where:
          ref: text_version
          shift: [0, +1.5]
          rotate: 0

outlines:

  # Pure key outline.
  raw:
    - what: rectangle
      where: true
      size: [px, py]

  # Key outlines with 0.5mm removed to show key overlaps.
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]

  # Actual outline of the board
  board:
    - what: polygon
      operation: stack
      fillet: 1
      points:

        # Top
        # Outer
        - ref: matrix_outer_top
          shift: [-kxo - pcb_outline_padding_left, +kyo + pcb_outline_padding_top]
        - ref: matrix_outer_top
          shift: [+kxo, +kyo + pcb_outline_padding_top]

        # Pinky
        - ref: matrix_pinky_top
          shift: [-kxo, +kyo + pcb_outline_padding_top]
        - ref: matrix_pinky_top
          shift: [+kxo, +kyo + pcb_outline_padding_top]

        # Ring
        - ref: matrix_ring_top
          shift: [-kxo, +kyo + pcb_outline_padding_top]
        - ref: matrix_ring_top
          shift: [+kxo, +kyo + pcb_outline_padding_top]

        # Middle
        - ref: matrix_middle_top
          shift: [-kxo, +kyo + pcb_outline_padding_top]
        - ref: matrix_middle_top
          shift: [+kxo, +kyo + pcb_outline_padding_top]

        # Index
        - ref: matrix_index_top
          shift: [-kxo, +kyo + pcb_outline_padding_top]
        - ref: matrix_index_top
          shift: [+kxo, +kyo + pcb_outline_padding_top]

        # Inner
        - ref: matrix_inner_top
          shift: [-kxo, +kyo + pcb_outline_padding_top]
        - ref: matrix_inner_top
          shift: [+kxo, +kyo + pcb_outline_padding_top]

        # Controller
        - ref: mcu
          shift: [-mcu_xo - mcu_spacing_left, +mcu_yo]
        - ref: mcu
          shift: [+mcu_xo + mcu_spacing_right, +mcu_yo]

        # Right Side
        # Inner Thumb
        - ref: edge_thumb_cluster_top
          shift: [0, 0]
        - ref: edge_thumb_cluster_bottom
          shift: [0 - pcb_outline_padding_bottom, 0]

        # Bottom
        # Inner thumb
        - ref: thumbs_inner_cluster
          shift: [-inner_thumb_xo - pcb_outline_padding_bottom, +inner_thumb_yo]

        # Outer Thumb
        - ref: thumbs_outer_cluster
          shift: [-kxo, -kyo - pcb_outline_padding_bottom]

        # Pinky y and ring x
        - ref: matrix_pinky_bottom
          shift: [kxo + 1kx, -kyo - pcb_outline_padding_bottom]

        # Outer
        - ref: matrix_outer_bottom
          shift: [-kxo - pcb_outline_padding_left, -kyo - pcb_outline_padding_bottom]

  # Combination preview showing outline and keys.
  combo:
    - name: board
    - operation: subtract
      name: keys
